### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by arifje** [balazscsaba2006/craft3-sharedcount#1]
![screen shot 2018-07-05 at 09 09 34](https://user-images.githubusercontent.com/1286410/42307594-391a53c0-8033-11e8-8b77-77159b0eda33.jpg)

Craft CMS 3.0.14

**Comment by balazscsaba2006** [comment]
@skoften Same as https://github.com/balazscsaba2006/craft3-cookiebot/issues/2

**Comment by balazscsaba2006** [comment]
Fixed in https://github.com/balazscsaba2006/craft3-sharedcount/releases/tag/1.0.2
